config/routes.rb
Rails.application.routes.draw do

  root 'farmlogs#index'

  resources :farmlogs
  devise_for :users

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
end

app/models/farmlog.rb
class Farmlog < ActiveRecord::Base
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :shot, ShotUploader


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/farmlogs_controller.rb
class FarmlogsController < ApplicationController
  before_action :set_farmlog, only: [:show, :edit, :update, :destroy]

  # GET /farmlogs
  # GET /farmlogs.json
  def index
    @farmlogs = Farmlog.all
  end

  # GET /farmlogs/1
  # GET /farmlogs/1.json
  def show
  end

  # GET /farmlogs/new
  def new
    @farmlog = Farmlog.new
  end

  # GET /farmlogs/1/edit
  def edit
  end

  # POST /farmlogs
  # POST /farmlogs.json
  def create
    @farmlog = Farmlog.new(farmlog_params)

    respond_to do |format|
      if @farmlog.save
        format.html { redirect_to @farmlog, notice: 'Farmlog was successfully created.' }
        format.json { render :show, status: :created, location: @farmlog }
      else
        format.html { render :new }
        format.json { render json: @farmlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farmlogs/1
  # PATCH/PUT /farmlogs/1.json
  def update
    respond_to do |format|
      if @farmlog.update(farmlog_params)
        format.html { redirect_to @farmlog, notice: 'Farmlog was successfully updated.' }
        format.json { render :show, status: :ok, location: @farmlog }
      else
        format.html { render :edit }
        format.json { render json: @farmlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farmlogs/1
  # DELETE /farmlogs/1.json
  def destroy
    @farmlog.destroy
    respond_to do |format|
      format.html { redirect_to farmlogs_url, notice: 'Farmlog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farmlog
      @farmlog = Farmlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farmlog_params
      params.require(:farmlog).permit(:title, :user_id, :img, :picture, :picture_cache)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def show
	end

  def create
  	
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/farmlogs_helper.rb
module FarmlogsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/comment/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

app/views/comment/destroy.html.erb
<h1>Comment#destroy</h1>
<p>Find me in app/views/comment/destroy.html.erb</p>

app/views/farmlogs/_form.html.erb
<%= simple_form_for(@farmlog) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.association :user %>
    <%= f.input :img %>
    <%= f.input :photo, as: :file %>
    <%= f.hidden_field :picture_cache %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/farmlogs/edit.html.erb
<h1>Editing Farmlog</h1>

<%= render 'form' %>

<%= link_to 'Show', @farmlog %> |
<%= link_to 'Back', farmlogs_path %>

app/views/farmlogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Farmlogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Img</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @farmlogs.each do |farmlog| %>
      <tr>
        <td><%= farmlog.title %></td>
        <td><%= farmlog.user %></td>
        <td><%= farmlog.img %></td>
        <td><%= link_to 'Show', farmlog %></td>
        <td><%= link_to 'Edit', edit_farmlog_path(farmlog) %></td>
        <td><%= link_to 'Destroy', farmlog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Farmlog', new_farmlog_path %>

app/views/farmlogs/new.html.erb
<h1>New Farmlog</h1>

<%= render 'form' %>

<%= link_to 'Back', farmlogs_path %>

app/views/farmlogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @farmlog.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @farmlog.user %>
</p>

<p>
  <strong>Img:</strong>
  <%= @farmlog.img %>
</p>

<%= link_to 'Edit', edit_farmlog_path(@farmlog) %> |
<%= link_to 'Back', farmlogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Farmcamping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/show.html.erb
<h1>농활 프로젝트</h1>